//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.11 at 03:25:14 PM MEZ 
//

package org.mapsforge.preprocessing.automization;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for bbox-area-filter complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="bbox-area-filter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mapsforge.org/mapsforge-preprocessing-conf}sink-source">
 *       &lt;attribute name="minlat" use="required" type="{http://mapsforge.org/mapsforge-preprocessing-conf}latitude" />
 *       &lt;attribute name="minlon" use="required" type="{http://mapsforge.org/mapsforge-preprocessing-conf}longitude" />
 *       &lt;attribute name="maxlat" use="required" type="{http://mapsforge.org/mapsforge-preprocessing-conf}latitude" />
 *       &lt;attribute name="maxlon" use="required" type="{http://mapsforge.org/mapsforge-preprocessing-conf}longitude" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bbox-area-filter")
public class BboxAreaFilter extends SinkSource {

	@XmlAttribute(required = true)
	protected double minlat;
	@XmlAttribute(required = true)
	protected double minlon;
	@XmlAttribute(required = true)
	protected double maxlat;
	@XmlAttribute(required = true)
	protected double maxlon;

	/**
	 * Gets the value of the minlat property.
	 * 
	 */
	public double getMinlat() {
		return minlat;
	}

	/**
	 * Sets the value of the minlat property.
	 * 
	 */
	public void setMinlat(double value) {
		this.minlat = value;
	}

	/**
	 * Gets the value of the minlon property.
	 * 
	 */
	public double getMinlon() {
		return minlon;
	}

	/**
	 * Sets the value of the minlon property.
	 * 
	 */
	public void setMinlon(double value) {
		this.minlon = value;
	}

	/**
	 * Gets the value of the maxlat property.
	 * 
	 */
	public double getMaxlat() {
		return maxlat;
	}

	/**
	 * Sets the value of the maxlat property.
	 * 
	 */
	public void setMaxlat(double value) {
		this.maxlat = value;
	}

	/**
	 * Gets the value of the maxlon property.
	 * 
	 */
	public double getMaxlon() {
		return maxlon;
	}

	/**
	 * Sets the value of the maxlon property.
	 * 
	 */
	public void setMaxlon(double value) {
		this.maxlon = value;
	}

	@Override
	public String generate() {
		
		StringBuilder sb = new StringBuilder();		
		
		sb.append("--bb").append(" ");
		sb.append("left=").append(minlon).append(" ");
		sb.append("right=").append(maxlon).append(" ");
		sb.append("bottom=").append(minlat).append(" ");
		sb.append("top=").append(maxlat).append(" ");
				
		sb.append(super.generate());
		
		return sb.toString();
	}

}
