//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.11 at 03:25:14 PM MEZ 
//

package org.mapsforge.preprocessing.automization;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for pipeline complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pipeline">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://mapsforge.org/mapsforge-preprocessing-conf}source"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pipeline", propOrder = {
		"source"
})
public class Pipeline {

	/**
	 * The source of the pipeline. The point where the execution started.
	 */
	@XmlElementRef(name = "source", namespace = "http://mapsforge.org/mapsforge-preprocessing-conf", type = JAXBElement.class)
	protected JAXBElement<? extends Source> source;

	/**
	 * The name of the pipeline.
	 */
	@XmlAttribute(required = true)
	protected String name;

	/**
	 * Gets the value of the source property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link Source }{@code >}
	 *         {@link JAXBElement }{@code <}{@link ReadPbf }{@code >}
	 * 
	 */
	public JAXBElement<? extends Source> getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link Source }{@code >}
	 *            {@link JAXBElement }{@code <}{@link ReadPbf }{@code >}
	 * 
	 */
	public void setSource(JAXBElement<? extends Source> value) {
		this.source = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
