//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.11 at 03:25:14 PM MEZ 
//

package org.mapsforge.preprocessing.automization;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for polygon-area-filter complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="polygon-area-filter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mapsforge.org/mapsforge-preprocessing-conf}sink-source">
 *       &lt;attribute name="polygon-file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "polygon-area-filter")
public class PolygonAreaFilter
		extends SinkSource {

	@XmlAttribute(name = "polygon-file", required = true)
	protected String polygonFile;

	/**
	 * Gets the value of the polygonFile property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPolygonFile() {
		return polygonFile;
	}

	/**
	 * Sets the value of the polygonFile property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPolygonFile(String value) {
		this.polygonFile = value;
	}

	@Override
	public String generate() {
		StringBuilder sb = new StringBuilder();
		sb.append("--bp").append(" ");
		sb.append("file=").append(polygonFile).append(" ");
		return PolygonAreaFilter.class.getName();
	}

}
