//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.11 at 03:25:14 PM MEZ 
//

package org.mapsforge.preprocessing.automization;

import java.io.File;
import java.io.IOException;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for routinggraph-writer complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="routinggraph-writer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mapsforge.org/mapsforge-preprocessing-conf}sink">
 *      &lt;attribute name="way-types" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "routinggraph-writer")
public class RoutinggraphWriter extends Sink {

	@XmlAttribute(name = "way-types")
	private String wayTypes;

	/**
	 * Gets the value of the wayTypes property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWayTypes() {
		return wayTypes;
	}

	/**
	 * Sets the value of the wayTypes property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWayTypes(String value) {
		this.wayTypes = value;
	}

	@Override
	public String generate(List<String> md5List, String absoluteWorkingDirPath,
			String absoluteOutputDirPath) {

		StringBuilder sb = new StringBuilder();
		File outputFile = null;
		try {
			outputFile = FileOperation.createWriteFile(absoluteOutputDirPath, getFile());
		} catch (IOException e) {
			System.err.println("MapfileWriter can not write to file.");
			e.printStackTrace();
		}

		if (outputFile == null)
			throw new RuntimeException("An unexpected error occured. File is null.");

		// TODO: DEBUG
		System.out.println("DEBUG: routinggraphwriter: outputFile: "
				+ outputFile.getAbsolutePath());

		if (isMd5()) {
			md5List.add(outputFile.getAbsolutePath());
		}
		sb.append("--rgw").append(" ");
		sb.append("file=").append(outputFile.getAbsolutePath()).append(" ");
		if (wayTypes != null)
			sb.append("way-types").append(wayTypes).append(" ");

		return sb.toString();
	}

}
